### ISSUE TITLE
Add missing specific docs for properties using common $ref's

### ISSUE THREAD

**Issue by segfaultxavi** [nemtech/symbol-openapi#233]
In OpenAPI 3.0 any sibling of a `$ref` field is ignored: https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03

Therefore, whenever we use a common ref like `publicKey.yml` or `Height.yml` we only provide the **generic** description for these fields.
Example of the problem in `AccountLinkVotingKeyDTO.yml`:
```yaml
properties:
  publicKey:
    type: string
  startEpoch:
    $ref: "../../../schemas/FinalizationEpoch.yml"
  endEpoch:
    $ref: "../../../schemas/FinalizationEpoch.yml"
```
Both `startEpoch` and `endEpoch` are described in the docs as `Finalization Epoch`, because that's the description in `FinalizationEpoch.yml`.

However, there's a workaround using `allOf`:
```yaml
properties:
  publicKey:
    type: string
  startEpoch:
    allOf:
      - description: "Start Epoch"
      - $ref: "../../../schemas/FinalizationEpoch.yml"
  endEpoch:
  allOf:
    - description: "Finalization Epoch"
    - $ref: "../../../schemas/FinalizationEpoch.yml"
```

Using redoc.ly to generate the docs as we currently do, the higher-level description is used and the lower-level one ignored.

Using this workaround, we should add all the missing specific docs.
